/**
 * 
 */
package com.entity;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Contain the relationship between user and goods.
 * ProjectName：SecondaryTradingSystem ClassName：UserOwnGoods ClassDescription：
 * Author：Pancake CreateTime：2017年1月23日 下午4:20:20
 * 
 * @version
 */
public class UserOwnGoods {
	private int ugId;
	private int userId;
	private int goodsId;

	public UserOwnGoods() {
		super();
	}

	public UserOwnGoods(int ugId, int userId, int goodsId) {
		super();
		this.ugId = ugId;
		this.userId = userId;
		this.goodsId = goodsId;
	}

	/**
	 * This method is used to return a UserOwnGoods object owns properties set by ResultSet.
	 * @param rs: ResultSet generated by sql.
	 * @return A UserOwnGoods object.
	 * @throws SQLException
	 */
	public static UserOwnGoods setAllProperties(ResultSet rs)
			throws SQLException {
		UserOwnGoods userOwnGoods = new UserOwnGoods();
		userOwnGoods.setUgId(rs.getInt("ugId"));
		userOwnGoods.setUserId(rs.getInt("userId"));
		// For test.
		userOwnGoods.setGoodsId(rs.getInt("goodsId"));
		return userOwnGoods;
	}

	public int getUgId() {
		return ugId;
	}

	public void setUgId(int ugId) {
		this.ugId = ugId;
	}

	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getGoodsId() {
		return goodsId;
	}

	public void setGoodsId(int goodsId) {
		this.goodsId = goodsId;
	}

}
